import requests
import math
from datetime import datetime
from langchain_core.tools import tool

# ── Research Tools ───────────────────────────────────────
@tool
def search_web(query: str) -> str:
    """Search the web for current information about a topic."""
    try:
        url    = "https://api.duckduckgo.com/"
        params = {
            "q":             query,
            "format":        "json",
            "no_html":       "1",
            "skip_disambig": "1"
        }
        response = requests.get(url, params=params, timeout=10)
        data     = response.json()

        results = []
        if data.get("Abstract"):
            results.append(f"Summary: {data['Abstract']}")
        if data.get("RelatedTopics"):
            for topic in data["RelatedTopics"][:3]:
                if isinstance(topic, dict) and topic.get("Text"):
                    results.append(f"- {topic['Text']}")
        if data.get("Answer"):
            results.append(f"Answer: {data['Answer']}")

        return "\n".join(results) if results else f"No results for '{query}'"
    except Exception as e:
        return f"Search failed: {str(e)}"

@tool
def lookup_knowledge_base(topic: str) -> str:
    """Look up information about distributed systems, ML, and AI topics."""
    knowledge = {
        "kubernetes": """Kubernetes is a container orchestration platform.
        Strengths: Auto-scaling, self-healing, rolling updates, large ecosystem.
        Weaknesses: Complex setup, steep learning curve, resource overhead.
        Best for: Large-scale production deployments, microservices.""",

        "docker swarm": """Docker Swarm is Docker's native clustering solution.
        Strengths: Simple setup, native Docker integration, less overhead.
        Weaknesses: Limited features vs Kubernetes, smaller ecosystem.
        Best for: Smaller deployments, teams already using Docker Compose.""",

        "kafka": """Apache Kafka is a distributed event streaming platform.
        Strengths: High throughput, fault tolerant, message replay, scalable.
        Weaknesses: Complex operations, ZooKeeper dependency (older versions).
        Best for: Real-time data pipelines, event sourcing, log aggregation.""",

        "mlops": """MLOps applies DevOps to ML systems.
        Key practices: Experiment tracking, model versioning, CI/CD for models.
        Tools: MLflow, Weights & Biases, Kubeflow, Seldon.
        Challenges: Data versioning, model drift, reproducibility.""",

        "rag": """Retrieval Augmented Generation combines retrieval with LLM generation.
        Steps: Chunk documents, embed, store in vector DB, retrieve, generate.
        Benefits: Reduces hallucinations, enables domain-specific knowledge.
        Tools: ChromaDB, Pinecone, LangChain, LlamaIndex.""",

        "langchain": """LangChain is a framework for building LLM applications.
        Components: Chains, Agents, Memory, Tools, Vector stores.
        Use cases: Chatbots, RAG systems, agents, document processing.""",

        "langgraph": """LangGraph is a framework for building stateful multi-agent systems.
        Models workflows as graphs — nodes are actions, edges are transitions.
        Supports: Cyclic workflows, human-in-the-loop, multi-agent coordination.
        Built on top of LangChain.""",
    }

    topic_lower = topic.lower()
    for key, value in knowledge.items():
        if key in topic_lower or topic_lower in key:
            return value

    return f"No information found for '{topic}'"

@tool
def compare_technologies(tech1: str, tech2: str) -> str:
    """Compare two technologies side by side.
    Use this when asked to compare or contrast two tools or frameworks."""
    return f"""Comparison request: {tech1} vs {tech2}
    
Please look up both technologies using lookup_knowledge_base 
and synthesize a comparison covering:
1. Core purpose and use case
2. Key strengths
3. Key weaknesses  
4. When to choose each"""

# ── Writing Tools ────────────────────────────────────────
@tool
def format_report(
    title: str,
    summary: str,
    sections: str,
    conclusion: str
) -> str:
    """Format research notes into a structured report.
    Use this to create the final polished output."""
    timestamp = datetime.now().strftime("%Y-%m-%d")
    return f"""# {title}
*Generated: {timestamp}*

## Executive Summary
{summary}

## Analysis
{sections}

## Conclusion
{conclusion}

---
*Report generated by AI Research Assistant*"""

@tool
def calculate(expression: str) -> str:
    """Perform mathematical calculations."""
    try:
        allowed = {"__builtins__": {}, "math": math}
        result  = eval(expression, allowed)
        return f"{expression} = {result}"
    except Exception as e:
        return f"Error: {str(e)}"

# ── Tool sets per agent ───────────────────────────────────
RESEARCH_TOOLS = [search_web, lookup_knowledge_base, compare_technologies, calculate]
WRITER_TOOLS   = [format_report]
ALL_TOOLS      = [search_web, lookup_knowledge_base, compare_technologies,
                  calculate, format_report]